services:
  service1:
    build:
      context: ./main_app
    container_name: app
    ports:
      - "127.0.0.1:5000:5000"  # Set to run on localhost
    networks:
      - main_network
    volumes:
      - ./common:/app/common 
    environment:
      PYTHONPATH: "/app:/app/common"  # Set PYTHONPATH to include the common directory
      COMMON_TEMPLATES_DIR: "/app/common/templates"  # Set path to common templates directory
      COMMON_STATIC_DIR: "/app/common/static"  # Set path to common static directory
    deploy:
      resources:
        limits:
          memory: 150M

  service2:
    build:
      context: ./prediciton_services_LR
    container_name: LRapp
    ports:
      - "127.0.0.1:5001:5001"
    networks:
      - main_network
    volumes:
      - ./common:/app/common  
    environment:
      PYTHONPATH: "/app:/app/common"  
      COMMON_TEMPLATES_DIR: "/app/common/templates"  
      COMMON_STATIC_DIR: "/app/common/static" 
    deploy:
      resources:
        limits:
          memory: 250M

  service3:
    build:
      context: ./prediction_services_NB
    container_name: NBapp
    ports:
      - "127.0.0.1:5002:5002" 
    networks:
      - main_network
    volumes:
      - ./common:/app/common 
    environment:
      PYTHONPATH: "/app:/app/common"  
      COMMON_TEMPLATES_DIR: "/app/common/templates"  
      COMMON_STATIC_DIR: "/app/common/static"  
    deploy:
      resources:
        limits:
          memory: 250M
  service4:
    build:
      context: ./prediction_services_PA
    container_name: PAapp
    ports:
      - "127.0.0.1:5003:5003"  
    networks:
      - main_network
    volumes:
      - ./common:/app/common  
    environment:
      PYTHONPATH: "/app:/app/common"  
      COMMON_TEMPLATES_DIR: "/app/common/templates"  
      COMMON_STATIC_DIR: "/app/common/static"  
    deploy:
      resources:
        limits:
          memory: 250M


networks:
  main_network:
    driver: bridge
